# Generated by Django 2.1.2 on 2018-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20181215_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='test', max_length=42),
            preserve_default=False,
        ),
    ]
